name: Build Project
on:
  push:
    branches:
      - test
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: CheckOut
        id: checkOut
        uses: actions/checkout@v2

      - name: Install Dependence
        id: install-dependence
        shell: pwsh
        run: |
          pip install twine build

      - name: Build project
        id: build
        shell: pwsh
        run: |
          python3 -m build

      - name: Publish Package
        uses: Commandcracker/pypi-publish@v1
        with:
          user: ${{ secrets.PYPI_API_USER }}
          password: ${{ secrets.PYPI_API_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}